server:
  port: 7001
eureka:
  #server:
  #  enable-self-preservation: false  eureka自我保护机制
  instance:
    hostname: eureka7001.com   #服务端的实例名称
  #hostname: localhost #eureka 服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false 表示自己就是注册中心，维护实例，不检索实例
   # service-url:
   # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #服务url
   # 单机版 eureka-server-u-r-l-context:  http://${eureka.instance.hostname}:${server.port}/eureka/ #服务url
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
